<?php

use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_entity_operation_alter().
 */
function powerstack_page_builder_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'node') {
    // Adding an external operation
    $operations['edit'] = [
      'title' => t('Edit'),
      'url' => \Drupal\Core\Url::fromUri('http://frontend.power-stack.docksal.site/node/' . $entity->id() . '/edit'),
      'attributes' => [
        'target' => '_blank', // Optionally open in a new tab.
      ],
      'weight' => 1, 
    ];
    $operations['view'] = [
      'title' => t('View'),
      'url' => \Drupal\Core\Url::fromUri('http://frontend.power-stack.docksal.site/node/' . $entity->id()),
      'attributes' => [
        'target' => '_blank', // Optionally open in a new tab.
      ],
      'weight' => 0, 
    ];
  }
}

/**
 * Implements hook_views_pre_render().
 */
function powerstack_page_builder_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];

  if ($view->id() == 'content' && $view->current_display == 'page_1' && $field->field == 'title') {
    $nid = $variables['row']->nid;
    $url = Url::fromUri('http://frontend.power-stack.docksal.site/node/' . $nid, [
      'attributes' => [
        'target' => '_blank',
        'rel' => 'noopener noreferrer', // For security and performance reasons.
      ],
      'absolute' => TRUE,
    ]);

    $variables['output'] = Link::fromTextAndUrl(
      $variables['row']->_entity->label(),
      $url
    )->toString();
  }
}
