name: Testing
on: push
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd frontend && yarn
      - name: Run tests
        run: sh ./scripts/testing/frontend/tests.sh