# documentation: https://drupal.org
# slogan: Drupal Open Source Software
# tags: cms, blog, content, management, mysql
# logo: https://www.drupal.org/files/styles/grid-2-2x-square/public/announcements/drupal-evergreen-logo-280X280px%20%281%29_0.jpg?itok=PHpn6rCb

services:
  drupal:
    image: drupal:latest
    volumes:
      - drupal-files:/var/www/html
    environment:
      SERVICE_FQDN:
      DRUPAL_DB_HOST: mysql
      DRUPAL_DB_USER: $SERVICE_USER_DRUPAL
      DRUPAL_DB_PASSWORD: $SERVICE_PASSWORD_DRUPAL
      DRUPAL_DB_NAME: drupal
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $SERVICE_PASSWORD_ROOT
      MYSQL_DATABASE: drupal
      MYSQL_USER: $SERVICE_USER_DRUPAL
      MYSQL_PASSWORD: $SERVICE_PASSWORD_DRUPAL
